name: test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: gotest
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test code
      run: go test -v -cover -coverprofile=coverage.out -p 1 ./...

    - name: Upload coverage to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.SQLFILE_CODECOV_TOKEN }}
        name: coverage
        flags: unittests
        fail_ci_if_error: true
